### PR TITLE
NN pipelines

### PR DESCRIPTION
**Pull request by egolol**

### CODE REVIEW

**Comment by annacanal** [comment]
In the Pipeline Structural Classification, I get this error after pressing 'C', and starting the training:

```
Error using matlab.ui.control.Table/set
Error setting property 'Data' of class 'Table':
Data must be a two-dimensional matrix.

Error in PlotPropCell/update (line 735)
		                set(pl.table_value_cell{i, j}, ...

Error in PlotElement/update (line 1059)
		        pl.get('PP_DICT').getItem(prop).update()

Error in PlotElement/redraw (line 1080)
		        pl.update()

Error in PlotElement/draw/redraw (line 1006)
		        pl.redraw()
 
Error using PlotProp/refresh (line 976)
Error while evaluating Panel SizeChangedFcn.
```

Screenshot 2021-11-12 at 15 48 32

**Review by annacanal — CHANGES_REQUESTED** [review]
Some errors appear.

Also to start training, maybe we could have a button, and not the 'C' button

**Comment by annacanal** [comment]
This error appears in **Pipeline Structural Regression**, same as before:

```
Error using matlab.ui.control.Table/set
Error setting property 'Data' of class 'Table':
Data must be a two-dimensional matrix.

Error in PlotPropCell/update (line 735)
		                set(pl.table_value_cell{i, j}, ...

Error in PlotElement/update (line 1059)
		        pl.get('PP_DICT').getItem(prop).update()

Error in PlotElement/redraw (line 1080)
		        pl.update()

Error in PlotElement/draw/redraw (line 1006)
		        pl.redraw()
 
Error using PlotProp/refresh (line 976)
Error while evaluating Panel SizeChangedFcn.
```

**Comment by annacanal** [comment]
> This error appears in **Pipeline Structural Regression**, same as before:
> 
> ```
> Error using matlab.ui.control.Table/set
> Error setting property 'Data' of class 'Table':
> Data must be a two-dimensional matrix.
> 
> Error in PlotPropCell/update (line 735)
> 		                set(pl.table_value_cell{i, j}, ...
> 
> Error in PlotElement/update (line 1059)
> 		        pl.get('PP_DICT').getItem(prop).update()
> 
> Error in PlotElement/redraw (line 1080)
> 		        pl.update()
> 
> Error in PlotElement/draw/redraw (line 1006)
> 		        pl.redraw()
>  
> Error using PlotProp/refresh (line 976)
> Error while evaluating Panel SizeChangedFcn.
> ```

Also I don't see how to choose which variable to use on the regression

**Comment by annacanal** [comment]
The same in **Functional GNN classification**:
Screenshot 2021-11-12 at 16 04 23

**Review by annacanal — APPROVED** [review]

**Review by giovannivolpe — APPROVED** [review]

**Pull request merged**
