### PR TITLE
935 eg GUI comparisons groups

### PR DESCRIPTION
**Pull request by egolol**
How to check:
RUN braph2genesis.
In the workflow folder, choose any workflow that uses ComparisonGroup Multigraph or GraphWU.
Run an example file in the selected workflow that uses BUT/BUD or WU.
Use the command GUI on the comparison object: GUI(comparison_obj);

### CODE REVIEW

**Comment by annacanal** [comment]
This isnt finish right?
There is no button to select which measures to compare yet

**Comment by egolol** [comment]
> This isnt finish right?
> There is no button to select which measures to compare yet

As per discussion this was tested for ensemble not group

**Comment by annacanal** [comment]
This error appears in the Comparison of a measure when using CON_BUD, after getting stuck "comparing", when I close the GUI windows:

Index exceeds the number of array elements (0).

Error in PPCompareGroupCP/draw/cb_table_calculate (line 835)
		            x2 = normalized(1) + normalized(3);
 
Error while evaluating DestroyedObject Callback.

**Comment by annacanal** [comment]
> This error appears in the Comparison of a measure when using CON_BUD, after getting stuck "comparing", when I close the GUI windows:
> 
> Index exceeds the number of array elements (0).
> 
> Error in PPCompareGroupCP/draw/cb_table_calculate (line 835)
> x2 = normalized(1) + normalized(3);
> 
> Error while evaluating DestroyedObject Callback.

And when using CON_BUT:
Error using waitbar (line 103)
The second argument must be a message character vector or a handle to an existing waitbar.

Error in PPCompareGroupCP/draw/cb_table_calculate (line 829)
		                waitbar(extra, f, ['Measure: ' measure ' Calculated! ...']);
 
Error while evaluating DestroyedObject Callback.


CON_WU works ;)

**Comment by egolol** [comment]
CON and FUN should be tested in CompareEnsembles

**Comment by annacanal** [comment]
> CON and FUN should be tested in CompareEnsembles

Sorry I was using ST_WU and ST_BUD, I wrote it wrong here

**Pull request closed without merging**
