### PR TITLE
Measure ensembles

### PR DESCRIPTION
**Pull request by egolol**
Add Measure ensembles
They need to be tested for almost all type of compatible graphs:
remember to add MultigraphBUDEnsemble and MultigraphBUTEnsemble as compatible graphs, and tests

### CODE REVIEW

**Review by annacanal — COMMENTED** [review]
Add MultigraphBUDEnsemble and MultigraphBUTEnsemble to all measures

**Comment by c-yuwei** [comment]
bug_to_be_fixed_items
Quick-fix on 5 ensemble measures:
- BetweennessCentralityEnsemble
- ClusteringAvEnsemble
- ClusteringEnsemble
- DiameterEnsemble
- EccentricityEnsemble

**Comment by c-yuwei** [comment]
> bug_to_be_fixed_items
> 
> Quick-fix on 5 ensemble measures:
> * BetweennessCentralityEnsemble
> * ClusteringAvEnsemble
> * ClusteringEnsemble
> * DiameterEnsemble
> * EccentricityEnsemble

**Comment by c-yuwei** [comment]
Progress record

- [ ] Assortativity.m
- [ ]  BetweennessCentrality.m
- [ ] CategoricalPersistence.m
- [ ] ClusteringAv.m
- [ ] Clustering.m
- [ ] CommunityStructure.m
- [ ] DegreeAv.m
- [ ] Degree.m
- [ ] DegreeOverlapAv.m
- [ ] DegreeOverlap.m
- [ ] Diameter.m
- [ ] Distance.m
- [ ] EccentricityAv.m
- [ ] Eccentricity.m
- [ ] EdgeBetweennessCentrality.m
- [ ] EdgeNumberDistance.m
- [ ] EdgeOverlap.m
- [ ] EigenvectorCentrality.m
- [ ] GlobalEfficiencyAv.m
- [ ] GlobalEfficiency.m
- [ ] InDegreeAv.m
- [ ] InDegree.m
- [ ] InEccentricityAv.m
- [ ] InEccentricity.m
- [ ] InGlobalEfficiencyAv.m
- [ ] InGlobalEfficiency.m
- [ ] InInAssortativity.m
- [ ] InOutAssortativity.m
- [ ] InPathLengthAv.m
- [ ] InPathLength.m
- [ ] InStrengthAv.m
- [ ] InStrength.m
- [ ] KCore.m
- [ ] KCorenessCentrality.m
- [ ] LocalEfficiencyAv.m
- [ ] LocalEfficiency.m
- [ ] Modularity.m
- [ ] MultilayerCommunityStructure.m
- [ ] MultilayerModularity.m
- [ ] MultiplexClusteringAv.m
- [ ] MultiplexClustering.m
- [ ] MultiplexCorePeriphery.m
- [ ] MultiplexInParticipation.m
- [ ] MultiplexOutParticipation.m
- [ ] MultiplexParticipationAv.m
- [ ] MultiplexParticipation.m
- [ ] MultiplexTriangles.m
- [ ] MultiRichClubDegree.m
- [ ] MultiRichClubStrength.m
- [ ] Multirichness.m
- [ ] OutDegreeAv.m
- [ ] OutDegree.m
- [ ] OutEccentricityAv.m
- [ ] OutEccentricity.m
- [ ] OutGlobalEfficiencyAv.m
- [ ] OutGlobalEfficiency.m
- [ ] OutInAssortativity.m
- [ ] OutOutAssortativity.m
- [ ] OutPathLengthAv.m
- [ ] OutPathLength.m
- [ ] OutStrengthAv.m
- [ ] OutStrength.m
- [ ] OverlappingDegreeAv.m
- [ ] OverlappingDegree.m
- [ ] OverlappingInDegreeAv.m
- [ ] OverlappingInDegree.m
- [ ] OverlappingInStrengthAv.m
- [ ] OverlappingInStrength.m
- [ ] OverlappingOutDegreeAv.m
- [ ] OverlappingOutDegree.m
- [ ] OverlappingOutStrengthAv.m
- [ ] OverlappingOutStrength.m
- [ ] OverlappingStrengthAv.m
- [ ] OverlappingStrength.m
- [ ] Participation.m
- [ ] PathLengthAv.m
- [ ] PathLength.m
- [ ] PathTransitivity.m
- [ ] Radius.m
- [ ] RichClubDegree.m
- [ ] RichClub.m
- [ ] RichClubStrength.m
- [ ] Richness.m
- [ ] SCore.m
- [ ] SmallWorldness.m
- [ ] StrengthAv.m
- [ ] Strength.m
- [ ] Transitivity.m
- [ ] Triangles.m
- [ ] WeightedEdgeOverlap.m
- [ ] WeightedMultiplexInParticipation.m
- [ ] WeightedMultiplexOutParticipation.m
- [ ] WeightedMultiplexParticipationAv.m
- [ ] WeightedMultiplexParticipation.m
- [ ] WeightedRichClub.m

**Pull request merged**
