### PR TITLE
proposition of measurements

### PR DESCRIPTION
**Pull request by egolol**
NaN handling in braph measures

### CODE REVIEW

**Comment by annacanal** [comment]
@egolol 
So, the measures where you have commented on the NaN = 0, are the ones you think assigning zero is wrong?
And the measures you didn't comment, do you agree that assigning zero to the NaN is correct?
For example in multiplex participation NaN comes from degree = 0 and overlapping degree = 0; and then it makes sense to say that multiplex participation is zero in that node. Do you agree with?

**Comment by annacanal** [comment]
> in multiplex participation NaN comes from degree = 0 and overlapping degree = 0; and then it makes sense to say that multiplex participation is zero in that node. Do you agree with?

In fact, now reviewing the definition. I see in this case it **should be 1.**
If the node has the same degree in all layers, the Participation coefficient of the node (Pi) is equal to 1. On the contrary, if the links of node i are concentrated in one layer, Pi is equal to 0. In that case, in all layers the degree is equal zero

**Comment by egolol** [comment]
I did not review the multiplex measure because I think you know better.

**Comment by egolol** [comment]
I have not reviewed Multiplex yet.

**Comment by annacanal** [comment]
> I have not reviewed Multiplex yet.

Sorry, this afternoon I will write about Multiplex. I think no changes will have to be made.
Multiplex participation NaN assignation to zero is correct. I will check later all other measures of multiplex ;)

**Comment by annacanal** [comment]
The review for new measures like RichClub + multiplex measures with respect to NaN handling is done

**Comment by egolol** [comment]
Yeah, I have read the multi measures, the overlapping measures, and the new measures and I don't think they should be NaN, 0 is a good value.

**Review by giovannivolpe — CHANGES_REQUESTED** [review]
add comments to the header of each measure to explain in which cases they return NaN and why

**Review by giovannivolpe — CHANGES_REQUESTED** [review]
I get an error in test_OutGlobalEfficiency
Can you check it before I merge it?

**Review by giovannivolpe — APPROVED** [review]

**Pull request merged**
